### ISSUE TITLE
Terminology confusion between this tool and "sqlite-utils transform"

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-transform#11]
For the moment I'll call this out in the README. I wish I had picked different names!

**Comment by simonw** [comment]
https://github.com/simonw/sqlite-transform/blob/67249800b78c39d0ad32c09a39db97ceaf57eaea/README.md#terminology-warning

**Comment by simonw** [comment]
Renaming this tool "sqlite-convert" would help here.

Or: merge the functionality into a `sqlite-utils convert` command and retire `sqlite-transform` as a separate project entirely.

**Comment by mroswell** [comment]
I'd like to see a simple graphical illustration of the differences. Could be hand-drawn, for starters.

**Comment by simonw** [comment]
I shipped a new release of `sqlite-utils` with the `sqlite-utils convert` command that replaces `sqlite-utils transform` entirely: https://sqlite-utils.datasette.io/en/stable/cli.html#converting-data-in-columns

Release 3.14 changelog: https://sqlite-utils.datasette.io/en/stable/changelog.html#v3-14

I'm going to ship a final version of this tool that recommends using `sqlite-utils` instead.
